### PR TITLE
Merge weechat-scripts version

### PR DESCRIPTION
**Pull request by stacyharper**
While backporting the eval expression to weechat-scripts:

https://github.com/weechat/scripts/pull/555

I did notice that both version have diverged slightly.

This MR merge back it upstream here.

### CODE REVIEW

**Comment by stacyharper** [comment]
I know that this merge make the release flags to be a bit wrong. But both now live in two different dystopics, so I don't really know what is the best thing to do.

**Comment by mumixam** [comment]
sorry the delay. is there any reason you changed the tag line
from 
```tags = dict([s.split('=',1) for s in mp['tags'].split(';')])```
to
```tags = dict([s.split('=') for s in mp['tags'].split(';')])```

**Comment by stacyharper** [comment]
iirc because this was causing warning or deprecated message in the weechat log buffer. But I'm not sure anymore

**Comment by mumixam** [comment]
I believe those are unrelated as i've never seen them myself. what version of python are you using

**Comment by stacyharper** [comment]
Okay, dunno where I saw this :S

**Comment by mumixam** [comment]
ok i found out the reason i added the maxsplit of 1.

this was to fix issues when the chat message contained "="

added in this commit
https://github.com/mumixam/weechat-twitch/commit/3c54a7b4e91a3c0ecf438740a38ff0add1b75bb5

**Pull request closed without merging**
